name: Publish to Sonatype Snapshots
on:
  workflow_dispatch:
jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Build and upload artifacts
        run: ./gradlew publishMavenPublicationToSonatypeSnapshotsRepository
        env:
          sonatype_username: ${{ secrets.SONATYPE_USERNAME }}
          sonatype_password: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_key_id: ${{ secrets.GPG_KEY_ID }}
          GPG_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_private_password: ${{ secrets.GPG_PRIVATE_PASSWORD }}
